ecom_data_model:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: your_account
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      database: ECOM_DB
      warehouse: ECOM_WH
      schema: RAW
      threads: 10